using System;
using System.Diagnostics;
using System.IO;

class Program
{
    private static readonly string GeneratedBy = "GPT-5.1-Codex-Mini";

    static int Main()
    {
        Console.WriteLine("Advent of Code - Day 01 (GPT-5.1-Codex-Mini)");

        var folder = AppContext.BaseDirectory;
        var projectDir = Directory.GetParent(folder)!.Parent!.Parent!.Parent!.Parent!.FullName;

        var puzzlePath = Path.Combine(projectDir, "puzzle.txt");
        var inputPath = Path.Combine(projectDir, "input.txt");
        var samplePath = Path.Combine(projectDir, "sample.txt");
        var sampleExpectedPath = Path.Combine(projectDir, "sample.expected.txt");

        Console.WriteLine($"Project dir: {projectDir}");

        if (!File.Exists(inputPath))
        {
            Console.WriteLine("ERROR: input.txt not found. Please add your input to input.txt.");
            return 1;
        }

        var inputText = File.ReadAllText(inputPath);
        var sampleText = File.Exists(samplePath) ? File.ReadAllText(samplePath) : string.Empty;
        var sampleExpectedText = File.Exists(sampleExpectedPath) ? File.ReadAllText(sampleExpectedPath) : string.Empty;

        if (GeneratedBy == "REPLACE_WITH_MODEL_NAME")
        {
            Console.WriteLine("ERROR: GeneratedBy placeholder not replaced in Program.cs. Replace with model name used to generate this solution.");
            return 3;
        }

        var sw = Stopwatch.StartNew();
        try
        {
            var result = Solve(inputText);
            sw.Stop();

            Console.WriteLine($"Result: {result}");
            Console.WriteLine($"Elapsed: {sw.Elapsed}");
            Console.WriteLine($"Generated by: {GeneratedBy}");

            if (!string.IsNullOrEmpty(sampleText) || !string.IsNullOrEmpty(sampleExpectedText))
            {
                if (string.IsNullOrEmpty(sampleText) || string.IsNullOrEmpty(sampleExpectedText))
                {
                    Console.WriteLine("ERROR: sample.txt and sample.expected.txt must both be present for validation.");
                    return 4;
                }

                var sampleResult = Solve(sampleText);
                Console.WriteLine("-- Sample Result --");
                Console.WriteLine($"Sample Result: {sampleResult}");

                var normalizedExpected = sampleExpectedText.Replace("\r\n", "\n").Trim();
                var normalizedActual = sampleResult.Replace("\r\n", "\n").Trim();
                if (normalizedExpected != normalizedActual)
                {
                    Console.WriteLine("ERROR: Sample result did not match sample.expected.txt");
                    Console.WriteLine("Expected:\n" + normalizedExpected);
                    Console.WriteLine("Actual:\n" + normalizedActual);
                    return 5;
                }
                else
                {
                    Console.WriteLine("Sample validation passed.");
                }
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error during solve: {ex}");
            return 2;
        }
    }

    static string Solve(string input)
    {
        const int DialSize = 100;
        var lines = input.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);

        long part1Hits = 0;
        long part2Hits = 0;
        var position = 50;

        foreach (var line in lines)
        {
            var direction = line[0];
            var distance = long.Parse(line.AsSpan(1));
            var delta = direction == 'R' ? 1 : -1;

            var firstHit = direction == 'R'
                ? (DialSize - position) % DialSize
                : position % DialSize;
            if (firstHit == 0)
            {
                firstHit = DialSize;
            }

            if (distance >= firstHit)
            {
                part2Hits += 1 + (distance - firstHit) / DialSize;
            }

            var remainder = distance % DialSize;
            position = Mod(position + delta * remainder, DialSize);

            if (position == 0)
            {
                part1Hits++;
            }
        }

        return $"Part 1: {part1Hits}\nPart 2: {part2Hits}";
    }

    static int Mod(long value, int modulus)
    {
        var result = value % modulus;
        if (result < 0)
        {
            result += modulus;
        }

        return (int)result;
    }
}
