using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

class Program
{
    private static readonly string GeneratedBy = "Self";

    static int Main()
    {
        Console.WriteLine("Advent of Code - Day Template");

        var folder = AppContext.BaseDirectory;
        var projectDir = Directory.GetParent(folder)!.Parent!.Parent!.Parent!.Parent!.FullName;

        var puzzlePath = Path.Combine(projectDir, "puzzle.txt");
        var inputPath = Path.Combine(projectDir, "input.txt");
        var samplePath = Path.Combine(projectDir, "sample.txt");
        var sampleExpectedPath = Path.Combine(projectDir, "sample.expected.txt");

        Console.WriteLine($"Project dir: {projectDir}");

        // `puzzle.txt` is optional. The agent may read it offline to implement the solution,
        // but the running program must not rely on parsing it.
        if (!File.Exists(inputPath))
        {
            Console.WriteLine("ERROR: input.txt not found. Please add your input to input.txt.");
            return 1;
        }

        var inputText = File.ReadAllText(inputPath);
        var sampleText = File.Exists(samplePath) ? File.ReadAllText(samplePath) : string.Empty;
        var sampleExpectedText = File.Exists(sampleExpectedPath) ? File.ReadAllText(sampleExpectedPath) : string.Empty;

        if (GeneratedBy == "REPLACE_WITH_MODEL_NAME")
        {
            Console.WriteLine("ERROR: GeneratedBy placeholder not replaced in Program.cs. Replace with model name used to generate this solution.");
            return 3;
        }

        try
        {            
            // Validate sample if present. The assistant generating the day's folder must extract the example
            // from puzzle.txt into sample.txt and put the expected results into sample.expected.txt.
            if (!string.IsNullOrEmpty(sampleText) || !string.IsNullOrEmpty(sampleExpectedText))
            {
                if (string.IsNullOrEmpty(sampleText) || string.IsNullOrEmpty(sampleExpectedText))
                {
                    Console.WriteLine("ERROR: sample.txt and sample.expected.txt must both be present for validation.");
                    return 4;
                }

                var sampleResult = Solve(sampleText);
                Console.WriteLine("-- Sample Result --");
                Console.WriteLine($"Sample Result: {sampleResult}");

                // Normalize line endings for comparison
                var normalizedExpected = sampleExpectedText.Replace("\r\n", "\n").Trim();
                var normalizedActual = sampleResult.Replace("\r\n", "\n").Trim();
                if (normalizedExpected != normalizedActual)
                {
                    Console.WriteLine("ERROR: Sample result did not match sample.expected.txt");
                    Console.WriteLine("Expected:\n" + normalizedExpected);
                    Console.WriteLine("Actual:\n" + normalizedActual);
                    return 5;
                }
                else
                {
                    Console.WriteLine("Sample validation passed.");
                    Console.WriteLine();
                }
            }

            var sw = Stopwatch.StartNew();
            var result = Solve(inputText);
            sw.Stop();

            Console.WriteLine($"Result:\n{result}");
            Console.WriteLine($"Elapsed: {sw.Elapsed}");
            Console.WriteLine($"Generated by: {GeneratedBy}");

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error during solve: {ex}");
            return 2;
        }
    }

    // Example Solve for templating: replace this with day's solver. Returns both Part 1 and Part 2 in a single string.
    // The returned string should contain both results formatted as two lines: "Part 1: <answer>" and "Part 2: <answer>".
    // If Part 2 is not yet available, return "Part 2: Not yet available" as a placeholder.
    static string Solve(string input)
    {
        var lines = input.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
        
        var grid = new char[lines.Length][];
        for (int i = 0; i < lines.Length; i++){
            var row = lines[i].ToArray();
            grid[i] = row;
        }
        
        // Part 1 logic
        var part1 = 0;
        for (var x = 0; x < grid.Length; x++)
        {
            for (var y = 0; y < grid[x].Length; y++)
            {
                var current = grid[x][y];
                if (current != '@') continue;

                if (GetSurrounding(x, y, grid) < 4){
                    part1++;
                }
            }
        }
        
        // Part 2 logic (implement when Part 2 is revealed)
        var part2 = 0;
        var removed = false;
        var iteration = 0;
        do
        {
            Console.WriteLine($"--- Iteration {++iteration} ---");
            removed = false;
            for (var x = 0; x < grid.Length; x++)
            {
                for (var y = 0; y < grid[x].Length; y++)
                {
                    var current = grid[x][y];
                    if (current != '@') continue;

                    if (GetSurrounding(x, y, grid) < 4){
                        grid[x][y] = '.';
                        part2++;
                        removed = true;
                    }
                }
            }        
        } while (removed);
        return $"Part 1: {part1}\nPart 2: {part2}";
    }

    private static int GetSurrounding(int x, int y, char[][] grid)
    {
        var directions = new (int dx, int dy)[]
        {
            (-1, -1),
            (-1, 0),
            (-1, 1),
            (0, -1),
            (0, 1),
            (1, -1),
            (1, 0),
            (1, 1),
        };

        var ct = 0;

        foreach (var (dx, dy) in directions)
        {
            var newX = x + dx;
            var newY = y + dy;

            if (newX >= 0 && newX < grid.Length && 
                newY >= 0 && newY < grid[newX].Length &&
                grid[newX][newY] == '@')
            {
                ct++;
            }
        }

        return ct;
    }
}
