using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

class Program
{
    static int Main()
    {
        Console.WriteLine("Advent of Code - Day 01");

        var folder = AppContext.BaseDirectory;
        var projectDir = Directory.GetParent(folder)!.Parent!.Parent!.Parent!.Parent!.FullName;

        Console.WriteLine($"Folder: {projectDir}");

        var puzzlePath = Path.Combine(projectDir, "puzzle.txt");
        var inputPath = Path.Combine(projectDir, "input.txt");
        var samplePath = Path.Combine(projectDir, "sample.txt");

        Console.WriteLine($"Project dir: {projectDir}, {inputPath}");

        // `puzzle.txt` is optional. The agent may read it offline to implement the solution,
        // but the running program must not rely on parsing it.
        if (!File.Exists(inputPath))
        {
            Console.WriteLine("ERROR: input.txt not found. Please add your input to input.txt.");
            return 1;
        }

        var inputText = File.ReadAllText(inputPath);
        var sampleText = File.Exists(samplePath) ? File.ReadAllText(samplePath) : string.Empty;

        // Hard-coded model attribution: agent must replace this string in generated code with the model used.
        const string GeneratedBy = "SELF";

        var sw = Stopwatch.StartNew();
        try
        {
            var result1 = Solve1(inputText);
            sw.Stop();
            sw.Restart();
            var result2 = Solve2(inputText);
            sw.Stop();
            
            Console.WriteLine($"Result: {result1}");
            Console.WriteLine($"Elapsed: {sw.Elapsed}");
            Console.WriteLine($"Generated by: {GeneratedBy}");

            if (!string.IsNullOrEmpty(sampleText))
            {
                var sampleResult = Solve1(sampleText);
                Console.WriteLine("-- Sample Result --");
                Console.WriteLine($"Sample Result: {sampleResult}");
                Console.WriteLine("(Place expected result in sample.expected.txt to validate.)");
            }



            Console.WriteLine($"Result: {result2}");
            Console.WriteLine($"Elapsed: {sw.Elapsed}");
            Console.WriteLine($"Generated by: {GeneratedBy}");

            if (!string.IsNullOrEmpty(sampleText))
            {
                var sampleResult = Solve2(sampleText);
                Console.WriteLine("-- Sample Result --");
                Console.WriteLine($"Sample Result: {sampleResult}");
                Console.WriteLine("(Place expected result in sample.expected.txt to validate.)");
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error during solve: {ex}");
            return 2;
        }
    }

    static string Solve1(string input)
    {
        var result = 0;
        var running = 50;
        var numbers = input.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries).ToArray();

        foreach (var n in numbers)
        {
            var direction = n[0];
            var value = int.Parse(n[1..]);

            Console.WriteLine($"Direction: {direction}, Value: {value}");

            var sign = direction == 'R' ? 1 : -1;
            
            running += sign * value;
            running %= 100;
            if (running < 0){
                running += 100;
            }

            Console.Write($"Running: {running}");

            if (running == 0){
                result++;
                Console.Write(" -- SCORE INCREASED!");
            }

            Console.WriteLine();
        }

        return result.ToString();
    }

    static string Solve2(string input)
    {
        var result = 0;
        var running = 50;
        var numbers = input.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries).ToArray();

        foreach (var n in numbers)
        {
            var orig = running;
            var direction = n[0];
            var value = int.Parse(n[1..]);

            Console.Write($"Direction: {direction}, Value: {value}.");

            if (value > 100){
                result += (int)(value / 100);
                Console.Write($" Large move detected, adding {value / 100} to result.");
            }

            //Console.WriteLine($"Direction: {direction}, Value: {value}");

            var sign = direction == 'R' ? 1 : -1;
            
            running += sign * value;
            running %= 100;
            
            if (running < 0){
                running += 100;
            }

            if (orig == 0){
                //Do nothing
            }
            else if (direction == 'L' && (running > orig || running == 0)){
                result++;
                Console.Write(" Left turn passed zero, increasing score.");
            }
            else if (direction == 'R' && (running < orig || running == 0)){
                result++;
                Console.Write(" Right turn passed zero, increasing score.");
            }

            Console.WriteLine($" Running: {running}");
        }

        return result.ToString();
    }
}