using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

class Program
{
    private static readonly string GeneratedBy = "Self";

    static int Main()
    {
        Console.WriteLine("Advent of Code - Day Template");

        var folder = AppContext.BaseDirectory;
        var projectDir = Directory.GetParent(folder)!.Parent!.Parent!.Parent!.Parent!.FullName;

        var puzzlePath = Path.Combine(projectDir, "puzzle.txt");
        var inputPath = Path.Combine(projectDir, "input.txt");
        var samplePath = Path.Combine(projectDir, "sample.txt");
        var sampleExpectedPath = Path.Combine(projectDir, "sample.expected.txt");

        Console.WriteLine($"Project dir: {projectDir}");

        // `puzzle.txt` is optional. The agent may read it offline to implement the solution,
        // but the running program must not rely on parsing it.
        if (!File.Exists(inputPath))
        {
            Console.WriteLine("ERROR: input.txt not found. Please add your input to input.txt.");
            return 1;
        }

        var inputText = File.ReadAllText(inputPath);
        var sampleText = File.Exists(samplePath) ? File.ReadAllText(samplePath) : string.Empty;
        var sampleExpectedText = File.Exists(sampleExpectedPath) ? File.ReadAllText(sampleExpectedPath) : string.Empty;

        if (GeneratedBy == "REPLACE_WITH_MODEL_NAME")
        {
            Console.WriteLine("ERROR: GeneratedBy placeholder not replaced in Program.cs. Replace with model name used to generate this solution.");
            return 3;
        }

        try
        {            
            // Validate sample if present. The assistant generating the day's folder must extract the example
            // from puzzle.txt into sample.txt and put the expected results into sample.expected.txt.
            if (!string.IsNullOrEmpty(sampleText) || !string.IsNullOrEmpty(sampleExpectedText))
            {
                if (string.IsNullOrEmpty(sampleText) || string.IsNullOrEmpty(sampleExpectedText))
                {
                    Console.WriteLine("ERROR: sample.txt and sample.expected.txt must both be present for validation.");
                    return 4;
                }

                var sampleResult = Solve(sampleText);
                Console.WriteLine("-- Sample Result --");
                Console.WriteLine($"Sample Result: {sampleResult}");

                // Normalize line endings for comparison
                var normalizedExpected = sampleExpectedText.Replace("\r\n", "\n").Trim();
                var normalizedActual = sampleResult.Replace("\r\n", "\n").Trim();
                if (normalizedExpected != normalizedActual)
                {
                    Console.WriteLine("ERROR: Sample result did not match sample.expected.txt");
                    Console.WriteLine("Expected:\n" + normalizedExpected);
                    Console.WriteLine("Actual:\n" + normalizedActual);
                    return 5;
                }
                else
                {
                    Console.WriteLine("Sample validation passed.");
                    Console.WriteLine();
                }
            }

            var sw = Stopwatch.StartNew();
            var result = Solve(inputText);
            sw.Stop();

            Console.WriteLine($"Result:\n{result}");
            Console.WriteLine($"Elapsed: {sw.Elapsed}");
            Console.WriteLine($"Generated by: {GeneratedBy}");

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error during solve: {ex}");
            return 2;
        }
    }

    // Example Solve for templating: replace this with day's solver. Returns both Part 1 and Part 2 in a single string.
    // The returned string should contain both results formatted as two lines: "Part 1: <answer>" and "Part 2: <answer>".
    // If Part 2 is not yet available, return "Part 2: Not yet available" as a placeholder.
    static string Solve(string input)
    {
        var lines = input.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries).Select(x => x.ToString()).ToArray();
        var part1 = 0;

        // Part 1 logic
        foreach (var line in lines)
        {
            var f = 0;
            for (var x = 9; x >=1; x--)
            {               
                if (line.Contains(x.ToString()) && line.IndexOf(x.ToString()) < line.Length - 1)
                {
                    var xpos = line.IndexOf(x.ToString());
                    for (var y = 9; y >= 1; y--)
                    {
                        if (line.LastIndexOf(y.ToString()) > xpos)
                        {
                            f += y;
                            break;
                        }
                    }

                    f += x * 10;
                    break;
                }
            }
            Console.WriteLine($"{line} -> {f}");
            part1 += f;
        }
        
        // Part 2 logic (implement when Part 2 is revealed)
        long part2 = 0;
        
        foreach (var line in lines)
        {
            long f = 0;
            var search = line;
            var cur = "";
            for (var i = 0; i < 12; i++)
            {
                var max = 0;
                foreach (var digit in search[..^(11 - i)]) //Until the i digit from the end
                {
                    if (digit == '9') 
                    {
                        max = 9;
                        break;
                    }
                    var d = int.Parse(digit.ToString());
                    if (d > max)
                    {
                        max = d;
                    }
                }
                cur += max.ToString();
                search = search[(search.IndexOf(max.ToString()) + 1)..];
            }
            f = long.Parse(cur);
            Console.WriteLine($"{line} -> {f}");
            part2 += f;
        }
        
        return $"Part 1: {part1}\nPart 2: {part2}";
    }
}
