using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Text;

class Program
{
    private static readonly string GeneratedBy = "Claude Opus 4.5";

    static int Main()
    {
        Console.WriteLine("Advent of Code - Day 03: Lobby");

        var folder = AppContext.BaseDirectory;
        var projectDir = Directory.GetParent(folder)!.Parent!.Parent!.Parent!.Parent!.FullName;

        var puzzlePath = Path.Combine(projectDir, "puzzle.txt");
        var inputPath = Path.Combine(projectDir, "input.txt");
        var samplePath = Path.Combine(projectDir, "sample.txt");
        var sampleExpectedPath = Path.Combine(projectDir, "sample.expected.txt");

        Console.WriteLine($"Project dir: {projectDir}");

        if (!File.Exists(inputPath))
        {
            Console.WriteLine("ERROR: input.txt not found. Please add your input to input.txt.");
            return 1;
        }

        var inputText = File.ReadAllText(inputPath);
        var sampleText = File.Exists(samplePath) ? File.ReadAllText(samplePath) : string.Empty;
        var sampleExpectedText = File.Exists(sampleExpectedPath) ? File.ReadAllText(sampleExpectedPath) : string.Empty;

        if (GeneratedBy == "REPLACE_WITH_MODEL_NAME")
        {
            Console.WriteLine("ERROR: GeneratedBy placeholder not replaced in Program.cs. Replace with model name used to generate this solution.");
            return 3;
        }

        try
        {
            if (!string.IsNullOrEmpty(sampleText) || !string.IsNullOrEmpty(sampleExpectedText))
            {
                if (string.IsNullOrEmpty(sampleText) || string.IsNullOrEmpty(sampleExpectedText))
                {
                    Console.WriteLine("ERROR: sample.txt and sample.expected.txt must both be present for validation.");
                    return 4;
                }

                var sampleResult = Solve(sampleText);
                Console.WriteLine("-- Sample Result --");
                Console.WriteLine($"Sample Result:\n{sampleResult}");

                var normalizedExpected = sampleExpectedText.Replace("\r\n", "\n").Trim();
                var normalizedActual = sampleResult.Replace("\r\n", "\n").Trim();
                if (normalizedExpected != normalizedActual)
                {
                    Console.WriteLine("ERROR: Sample result did not match sample.expected.txt");
                    Console.WriteLine("Expected:\n" + normalizedExpected);
                    Console.WriteLine("Actual:\n" + normalizedActual);
                    return 5;
                }
                else
                {
                    Console.WriteLine("Sample validation passed.");
                    Console.WriteLine();
                }
            }

            var sw = Stopwatch.StartNew();
            var result = Solve(inputText);
            sw.Stop();

            Console.WriteLine($"Result:\n{result}");
            Console.WriteLine($"Elapsed: {sw.Elapsed}");
            Console.WriteLine($"Generated by: {GeneratedBy}");

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error during solve: {ex}");
            return 2;
        }
    }

    static string Solve(string input)
    {
        var lines = input.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);

        // Part 1: Turn on exactly 2 batteries per bank, form the largest 2-digit joltage
        // We need to pick two positions where the resulting 2-digit number is maximized
        // The first digit chosen must come before the second digit in the string
        long part1 = 0;
        foreach (var line in lines)
        {
            part1 += (long)GetMaxJoltage(line, 2);
        }

        // Part 2: Turn on exactly 12 batteries per bank, form the largest 12-digit joltage
        BigInteger part2 = 0;
        foreach (var line in lines)
        {
            part2 += GetMaxJoltage(line, 12);
        }

        return $"Part 1: {part1}\nPart 2: {part2}";
    }

    // Greedy algorithm to select 'count' digits from the string to form the maximum number
    // The digits must maintain their relative order (we can't rearrange)
    static BigInteger GetMaxJoltage(string bank, int count)
    {
        int n = bank.Length;
        if (count > n) return 0;

        var result = new StringBuilder();
        int startIdx = 0;

        for (int i = 0; i < count; i++)
        {
            // We need to pick (count - i) more digits
            // The current digit can be picked from startIdx to (n - (count - i - 1) - 1)
            // i.e., we must leave enough digits for the remaining picks
            int digitsNeeded = count - i;
            int lastValidIdx = n - digitsNeeded;

            char maxDigit = '0';
            int maxIdx = startIdx;

            for (int j = startIdx; j <= lastValidIdx; j++)
            {
                if (bank[j] > maxDigit)
                {
                    maxDigit = bank[j];
                    maxIdx = j;
                    if (maxDigit == '9') break; // Can't do better than 9
                }
            }

            result.Append(maxDigit);
            startIdx = maxIdx + 1;
        }

        return BigInteger.Parse(result.ToString());
    }
}
