using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;

class Program
{
    private static readonly string GeneratedBy = "Claude Haiku 4.5";

    static int Main()
    {
        Console.WriteLine("Advent of Code - Day 4: Printing Department");

        var folder = AppContext.BaseDirectory;
        var projectDir = Directory.GetParent(folder)!.Parent!.Parent!.Parent!.Parent!.FullName;

        var puzzlePath = Path.Combine(projectDir, "puzzle.txt");
        var inputPath = Path.Combine(projectDir, "input.txt");
        var samplePath = Path.Combine(projectDir, "sample.txt");
        var sampleExpectedPath = Path.Combine(projectDir, "sample.expected.txt");

        Console.WriteLine($"Project dir: {projectDir}");

        // `puzzle.txt` is optional. The agent may read it offline to implement the solution,
        // but the running program must not rely on parsing it.
        if (!File.Exists(inputPath))
        {
            Console.WriteLine("ERROR: input.txt not found. Please add your input to input.txt.");
            return 1;
        }

        var inputText = File.ReadAllText(inputPath);
        var sampleText = File.Exists(samplePath) ? File.ReadAllText(samplePath) : string.Empty;
        var sampleExpectedText = File.Exists(sampleExpectedPath) ? File.ReadAllText(sampleExpectedPath) : string.Empty;

        if (GeneratedBy == "REPLACE_WITH_MODEL_NAME")
        {
            Console.WriteLine("ERROR: GeneratedBy placeholder not replaced in Program.cs. Replace with model name used to generate this solution.");
            return 3;
        }

        try
        {            
            // Validate sample if present. The assistant generating the day's folder must extract the example
            // from puzzle.txt into sample.txt and put the expected results into sample.expected.txt.
            if (!string.IsNullOrEmpty(sampleText) || !string.IsNullOrEmpty(sampleExpectedText))
            {
                if (string.IsNullOrEmpty(sampleText) || string.IsNullOrEmpty(sampleExpectedText))
                {
                    Console.WriteLine("ERROR: sample.txt and sample.expected.txt must both be present for validation.");
                    return 4;
                }

                var sampleResult = Solve(sampleText);
                Console.WriteLine("-- Sample Result --");
                Console.WriteLine($"Sample Result: {sampleResult}");

                // Normalize line endings for comparison
                var normalizedExpected = sampleExpectedText.Replace("\r\n", "\n").Trim();
                var normalizedActual = sampleResult.Replace("\r\n", "\n").Trim();
                if (normalizedExpected != normalizedActual)
                {
                    Console.WriteLine("ERROR: Sample result did not match sample.expected.txt");
                    Console.WriteLine("Expected:\n" + normalizedExpected);
                    Console.WriteLine("Actual:\n" + normalizedActual);
                    return 5;
                }
                else
                {
                    Console.WriteLine("Sample validation passed.");
                    Console.WriteLine();
                }
            }

            var sw = Stopwatch.StartNew();
            var result = Solve(inputText);
            sw.Stop();

            Console.WriteLine($"Result:\n{result}");
            Console.WriteLine($"Elapsed: {sw.Elapsed}");
            Console.WriteLine($"Generated by: {GeneratedBy}");

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error during solve: {ex}");
            return 2;
        }
    }

    static string Solve(string input)
    {
        var lines = input.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
        
        if (lines.Length == 0)
            return "Part 1: 0\nPart 2: 0";
        
        var grid = lines.Select(l => l.ToCharArray()).ToArray();
        int height = grid.Length;
        int width = grid[0].Length;
        
        // Part 1: Count rolls that can be accessed (fewer than 4 rolls in 8 adjacent positions)
        int part1 = CountAccessible(grid, height, width);
        
        // Part 2: Simulate removal process
        var gridCopy = grid.Select(r => r.ToArray()).ToArray();
        int part2 = SimulateRemoval(gridCopy, height, width);
        
        return $"Part 1: {part1}\nPart 2: {part2}";
    }
    
    static int CountAccessible(char[][] grid, int height, int width)
    {
        int count = 0;
        for (int r = 0; r < height; r++)
        {
            for (int c = 0; c < width; c++)
            {
                if (grid[r][c] == '@' && CanAccess(grid, r, c, height, width))
                {
                    count++;
                }
            }
        }
        return count;
    }
    
    static bool CanAccess(char[][] grid, int r, int c, int height, int width)
    {
        int adjacentRolls = 0;
        for (int dr = -1; dr <= 1; dr++)
        {
            for (int dc = -1; dc <= 1; dc++)
            {
                if (dr == 0 && dc == 0) continue;
                int nr = r + dr;
                int nc = c + dc;
                if (nr >= 0 && nr < height && nc >= 0 && nc < width && grid[nr][nc] == '@')
                {
                    adjacentRolls++;
                }
            }
        }
        return adjacentRolls < 4;
    }
    
    static int SimulateRemoval(char[][] grid, int height, int width)
    {
        int totalRemoved = 0;
        bool changed = true;
        
        while (changed)
        {
            changed = false;
            var toRemove = new List<(int r, int c)>();
            
            // Find all accessible rolls
            for (int r = 0; r < height; r++)
            {
                for (int c = 0; c < width; c++)
                {
                    if (grid[r][c] == '@' && CanAccess(grid, r, c, height, width))
                    {
                        toRemove.Add((r, c));
                    }
                }
            }
            
            // Remove them
            if (toRemove.Count > 0)
            {
                changed = true;
                foreach (var (r, c) in toRemove)
                {
                    grid[r][c] = '.';
                    totalRemoved++;
                }
            }
        }
        
        return totalRemoved;
    }
}
