using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;

class Program
{
    private static readonly string GeneratedBy = "Claude Opus 4.5";

    static int Main()
    {
        Console.WriteLine("Advent of Code - Day 05");

        var folder = AppContext.BaseDirectory;
        var projectDir = Directory.GetParent(folder)!.Parent!.Parent!.Parent!.Parent!.FullName;

        var puzzlePath = Path.Combine(projectDir, "puzzle.txt");
        var inputPath = Path.Combine(projectDir, "input.txt");
        var samplePath = Path.Combine(projectDir, "sample.txt");
        var sampleExpectedPath = Path.Combine(projectDir, "sample.expected.txt");

        Console.WriteLine($"Project dir: {projectDir}");

        if (!File.Exists(inputPath))
        {
            Console.WriteLine("ERROR: input.txt not found. Please add your input to input.txt.");
            return 1;
        }

        var inputText = File.ReadAllText(inputPath);
        var sampleText = File.Exists(samplePath) ? File.ReadAllText(samplePath) : string.Empty;
        var sampleExpectedText = File.Exists(sampleExpectedPath) ? File.ReadAllText(sampleExpectedPath) : string.Empty;

        if (GeneratedBy == "REPLACE_WITH_MODEL_NAME")
        {
            Console.WriteLine("ERROR: GeneratedBy placeholder not replaced in Program.cs. Replace with model name used to generate this solution.");
            return 3;
        }

        try
        {
            if (!string.IsNullOrEmpty(sampleText) || !string.IsNullOrEmpty(sampleExpectedText))
            {
                if (string.IsNullOrEmpty(sampleText) || string.IsNullOrEmpty(sampleExpectedText))
                {
                    Console.WriteLine("ERROR: sample.txt and sample.expected.txt must both be present for validation.");
                    return 4;
                }

                var sampleResult = Solve(sampleText);
                Console.WriteLine("-- Sample Result --");
                Console.WriteLine($"Sample Result: {sampleResult}");

                var normalizedExpected = sampleExpectedText.Replace("\r\n", "\n").Trim();
                var normalizedActual = sampleResult.Replace("\r\n", "\n").Trim();
                if (normalizedExpected != normalizedActual)
                {
                    Console.WriteLine("ERROR: Sample result did not match sample.expected.txt");
                    Console.WriteLine("Expected:\n" + normalizedExpected);
                    Console.WriteLine("Actual:\n" + normalizedActual);
                    return 5;
                }
                else
                {
                    Console.WriteLine("Sample validation passed.");
                    Console.WriteLine();
                }
            }

            var sw = Stopwatch.StartNew();
            var result = Solve(inputText);
            sw.Stop();

            Console.WriteLine($"Result:\n{result}");
            Console.WriteLine($"Elapsed: {sw.Elapsed}");
            Console.WriteLine($"Generated by: {GeneratedBy}");

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error during solve: {ex}");
            return 2;
        }
    }

    static string Solve(string input)
    {
        // Parse input - split into ranges section and ingredient IDs section
        var sections = input.Replace("\r\n", "\n").Split("\n\n", StringSplitOptions.RemoveEmptyEntries);
        
        // Parse fresh ranges (format: "start-end")
        var rangeLines = sections[0].Split('\n', StringSplitOptions.RemoveEmptyEntries);
        var ranges = new List<(long start, long end)>();
        foreach (var line in rangeLines)
        {
            var parts = line.Split('-');
            ranges.Add((long.Parse(parts[0]), long.Parse(parts[1])));
        }

        // Part 1: Count how many available ingredient IDs are fresh
        long part1 = 0;
        if (sections.Length > 1)
        {
            var ingredientLines = sections[1].Split('\n', StringSplitOptions.RemoveEmptyEntries);
            foreach (var line in ingredientLines)
            {
                var id = long.Parse(line);
                if (ranges.Any(r => id >= r.start && id <= r.end))
                {
                    part1++;
                }
            }
        }

        // Part 2: Count total unique fresh IDs across all ranges
        // Merge overlapping ranges to avoid counting duplicates
        var sortedRanges = ranges.OrderBy(r => r.start).ThenBy(r => r.end).ToList();
        var mergedRanges = new List<(long start, long end)>();
        
        foreach (var range in sortedRanges)
        {
            if (mergedRanges.Count == 0)
            {
                mergedRanges.Add(range);
            }
            else
            {
                var last = mergedRanges[^1];
                // Check if ranges overlap or are adjacent
                if (range.start <= last.end + 1)
                {
                    // Merge by extending the last range
                    mergedRanges[^1] = (last.start, Math.Max(last.end, range.end));
                }
                else
                {
                    mergedRanges.Add(range);
                }
            }
        }

        // Count total IDs in merged ranges
        long part2 = 0;
        foreach (var range in mergedRanges)
        {
            part2 += range.end - range.start + 1;
        }

        return $"Part 1: {part1}\nPart 2: {part2}";
    }
}
